language: ruby
rvm:
  - 2.5
  - 2.2.2

cache: bundler

branches:
  # Only build master and release version tags
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

gemfile:
  - Gemfile
  - gemfiles/activerecord_5.2.gemfile
  - gemfiles/activerecord_5.1.gemfile
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/sidekiq_5.gemfile
  - gemfiles/sidekiq_4.gemfile
  - gemfiles/sidekiq_3.gemfile

script:
  - bundle exec rake spec

env:
  RACK_ENV: ""
  RAILS_ENV: ""
