language: ruby
rvm:
  - 2.6

cache: bundler

branches:
  # Only build master and release version tags
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

gemfile:
  - Gemfile

matrix:
  include:
    - rvm: 2.2.2
      gemfile:
        - gemfiles/activerecord_4.1.gemfile
        - gemfiles/activerecord_4.0.gemfile
        - gemfiles/sidekiq_3.gemfile
    - rvm: 2.5
      gemfile:
        - gemfiles/activerecord_5.2.gemfile
        - gemfiles/activerecord_5.1.gemfile
        - gemfiles/activerecord_5.0.gemfile
        - gemfiles/activerecord_4.2.gemfile
        - gemfiles/sidekiq_5.gemfile
        - gemfiles/sidekiq_4.gemfile

script:
  - bundle exec rake spec

env:
  RACK_ENV: ""
  RAILS_ENV: ""
