language: ruby

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

cache: bundler

branches:
  # Only build master and release version tags
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    - travis

rvm:
  - "2.6"

gemfile:
  - Gemfile

matrix:
  include:
  - rvm: "2.6"
    gemfile: Gemfile

  - rvm: "2.5"
    gemfile: gemfiles/activerecord_5.2.gemfile
  - rvm: "2.5"
    gemfile: gemfiles/activerecord_5.1.gemfile
  - rvm: "2.5"
    gemfile: gemfiles/activerecord_5.0.gemfile
  - rvm: "2.5"
    gemfile: gemfiles/activerecord_4.2.gemfile
  - rvm: "2.5"
    gemfile: gemfiles/sidekiq_5.gemfile
  - rvm: "2.5"
    gemfile: gemfiles/sidekiq_4.gemfile

  - rvm: "2.2.2"
    gemfile: gemfiles/activerecord_4.1.gemfile
  - rvm: "2.2.2"
    gemfile: gemfiles/activerecord_4.0.gemfile
  - rvm: "2.2.2"
    gemfile: gemfiles/sidekiq_3.gemfile

script:
  - gem list bundler
  - bundle exec rake spec

env:
  RACK_ENV: ""
  RAILS_ENV: ""
